"use client";

import { useState } from "react";
import { Check, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select } from "@/components/ui/select";
import {
  MAX_CLIP_COUNT,
  PLAN_POST_PLATFORMS,
  plannedOutputs,
  plannedPostCount
} from "@/lib/pipeline/plan";
import type { PipelinePlan } from "@/lib/pipeline/types";
import { cn } from "@/lib/utils";

const CLIP_COUNT_OPTIONS = [3, 5, 10, 15, 20, 25, 30, 40, MAX_CLIP_COUNT];
const SLIDE_COUNT_OPTIONS = [0, 4, 6, 8, 10, 12, 15, 20];

function Toggle({
  on,
  label,
  disabled,
  onChange
}: {
  on: boolean;
  label: string;
  disabled?: boolean;
  onChange: (next: boolean) => void;
}) {
  return (
    <button
      type="button"
      role="switch"
      aria-checked={on}
      disabled={disabled}
      onClick={() => onChange(!on)}
      className={cn(
        "flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-medium transition disabled:opacity-40",
        on
          ? "border-emerald-400/40 bg-emerald-400/10 text-emerald-200"
          : "border-[var(--border)] text-[var(--muted-foreground)] hover:border-[var(--border-strong)] hover:text-white"
      )}
    >
      <span
        className={cn(
          "flex h-3.5 w-3.5 items-center justify-center rounded-full border",
          on ? "border-emerald-300 bg-emerald-400/30" : "border-white/25"
        )}
      >
        {on && <Check className="h-2.5 w-2.5" />}
      </span>
      {label}
    </button>
  );
}

/**
 * Gate one, before a byte is downloaded: what this stream is about to be turned
 * into, and the knobs that change it. The summary is generated by
 * `plannedOutputs`, the same function the server plans from, so what is promised
 * here is what the run does.
 */
export function PlanCard({
  plan,
  editable,
  busy,
  onStart
}: {
  plan: PipelinePlan;
  /** False once the run has started — the plan becomes a record of what was agreed. */
  editable: boolean;
  busy: boolean;
  onStart: (plan: PipelinePlan) => void;
}) {
  // Seeded once: the poll that refreshes the run must not overwrite an edit
  // half-made. Opening a different run remounts this card (keyed on the run id),
  // and a started run reads its plan straight off the record.
  const [draft, setDraft] = useState<PipelinePlan>(plan);
  const shown = editable ? draft : plan;
  const outputs = plannedOutputs(shown);
  const patch = (next: Partial<PipelinePlan>) =>
    setDraft((current) => {
      const merged = { ...current, ...next };
      // The MP3 is cut out of the long-form export, so it cannot outlive it.
      if (!merged.longform) merged.audio = false;
      return merged;
    });

  return (
    <div className="mt-3 space-y-4">
      <ul className="space-y-1.5">
        {outputs.map((output) => (
          <li key={output.key} className="flex gap-2 text-xs">
            <span
              className={cn(
                "mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full",
                output.enabled ? "bg-emerald-400" : "bg-white/20"
              )}
            />
            <span className="min-w-0">
              <span className={cn("font-medium", output.enabled ? "text-white/90" : "text-[var(--muted-foreground)]")}>
                {output.label}
              </span>
              <span className="text-[var(--muted-foreground)]"> — {output.detail}</span>
            </span>
          </li>
        ))}
      </ul>

      {editable && (
        <>
          <div className="grid gap-3 sm:grid-cols-2">
            <label className="block">
              <span className="mb-1 block text-[11px] font-medium uppercase tracking-[0.14em] text-[var(--muted-foreground)]">
                Clips
              </span>
              <Select
                value={shown.clipCount}
                onChange={(event) => patch({ clipCount: Number(event.target.value) })}
                className="h-9 text-xs"
              >
                {CLIP_COUNT_OPTIONS.map((count) => (
                  <option key={count} value={count}>
                    {count} clips
                  </option>
                ))}
              </Select>
            </label>
            <label className="block">
              <span className="mb-1 block text-[11px] font-medium uppercase tracking-[0.14em] text-[var(--muted-foreground)]">
                Carousel
              </span>
              <Select
                value={shown.carouselSlides}
                onChange={(event) => patch({ carouselSlides: Number(event.target.value) })}
                className="h-9 text-xs"
              >
                {SLIDE_COUNT_OPTIONS.map((count) => (
                  <option key={count} value={count}>
                    {count === 0 ? "No carousel" : `${count} slides`}
                  </option>
                ))}
              </Select>
            </label>
          </div>

          <div className="flex flex-wrap gap-2">
            <Toggle on={shown.longform} label="Long-form edit" onChange={(next) => patch({ longform: next })} />
            <Toggle
              on={shown.audio}
              label="Podcast MP3"
              disabled={!shown.longform}
              onChange={(next) => patch({ audio: next })}
            />
            <Toggle on={shown.segments} label="Topic segments" onChange={(next) => patch({ segments: next })} />
            <Toggle on={shown.visualAd} label="Visual ad brief" onChange={(next) => patch({ visualAd: next })} />
          </div>

          <div>
            <span className="mb-1.5 block text-[11px] font-medium uppercase tracking-[0.14em] text-[var(--muted-foreground)]">
              Text posts {plannedPostCount(shown) > 0 ? `· ${plannedPostCount(shown)}` : ""}
            </span>
            <div className="flex flex-wrap gap-2">
              {PLAN_POST_PLATFORMS.map((entry) => (
                <Toggle
                  key={entry.platform}
                  on={shown.postPlatforms.includes(entry.platform)}
                  label={`${entry.label} · ${entry.count}`}
                  onChange={(next) =>
                    patch({
                      postPlatforms: next
                        ? [...shown.postPlatforms, entry.platform]
                        : shown.postPlatforms.filter((platform) => platform !== entry.platform)
                    })
                  }
                />
              ))}
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-3">
            <Button onClick={() => onStart(draft)} disabled={busy} className="px-4 py-2 text-xs">
              {busy ? <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" /> : null}
              Start the run
            </Button>
            <span className="text-[11px] text-[var(--muted-foreground)]">
              Nothing is downloaded until you do.
            </span>
          </div>
        </>
      )}
    </div>
  );
}
